language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t lebaothinh/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true lebaothinh/docker-react yarn test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-620308454651"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
